### ISSUE TITLE
[BUG] Invoking `mogrify` under this action is failing due to the Alpine base image being unpinned

### ISSUE THREAD

**Issue by webknjaz** [jruipinto/ImageMagick-action#3]
In my GHA workflow job, I pin this action as `jruipinto/ImageMagick-action@f8361c3ab427051432299cef10d7c76424f7ff6d` so it always uses the same commit from this repo.
However, it started failing some time between Nov 14, 2023 and 4 days ago: https://github.com/webknjaz/.me/actions/runs/7494665020/job/20495101900?pr=16#step:6:13.
```console
mogrify: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1924.
mogrify: unable to open file '/tmp/magick-JTeit1K0sy1Y72OTtguyQbrCfuFDBLkA': No such file or directory @ error/constitute.c/ReadImage/785.
mogrify: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1924.
mogrify: unable to open file '/tmp/magick-7QACmJG1-4xlbzhou_r9cPR_njJGdBnA': No such file or directory @ error/constitute.c/ReadImage/785.
```

The problem exists because docker-based actions always build fresh containers without any caching on each CI run (unless a pre-existing external container is referenced in `action.yml` in place of a dockerfile).

The last successful run was using the following container pin:
```console
#5 [1/5] FROM docker.io/library/alpine@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
```

A quick hotfix should be pinning the base container at https://github.com/jruipinto/ImageMagick-action/blob/f8361c3/Dockerfile#L1 to said hash. In the long run, though, a deeper compatibility investigation is needed.

**Comment by jruipinto** [comment]
I don't have the time to spend, currently, but please, add a PR and I'll review and merge it

**Comment by webknjaz** [comment]
#5 should do it

**Comment by webknjaz** [comment]
I migrated to https://github.com/marketplace/actions/setup-imagemagick and it works.
